language: go
go:
  - tip
before_install:
  - git clone git://github.com/hcatlin/libsass.git
  - cd libsass
  - autoreconf -i
  - ./configure
  - make && sudo make install
  - sudo cp sass_interface.h  /usr/include/
  - sudo cp sass.h /usr/local/include/
  - cd ..
script:
  - go test
  - go build
