language: go
go:
  - tip
before_install:
  - git clone git://github.com/hcatlin/libsass.git
  - cd libsass
  - make && sudo make install
  - sudo cp *.* /usr/include
  - cd ..
script:
  - go test
  - go build
